version: 1.0.6
files:
  - url: 菲尼合同引擎-1.0.6-x64.exe
    sha512: GNBGkQ3RSnkj5PZaRKvY9G2gKjPPPr2qlAYJgvWBAITE9wa1afG6X4Tr5uC751eCPJGyxm2sapCdTQuNAqd/cw==
    size: 74859459
path: 菲尼合同引擎-1.0.6-x64.exe
sha512: GNBGkQ3RSnkj5PZaRKvY9G2gKjPPPr2qlAYJgvWBAITE9wa1afG6X4Tr5uC751eCPJGyxm2sapCdTQuNAqd/cw==
releaseDate: '2026-06-03T06:46:53.778Z'
